CREATE DATABASE bbuc_wifi;
USE bbuc_wifi;
CREATE TABLE admins(id INT AUTO_INCREMENT PRIMARY KEY,username VARCHAR(50),password VARCHAR(255),role VARCHAR(30));
CREATE TABLE audit_logs(id INT AUTO_INCREMENT PRIMARY KEY,admin VARCHAR(50),action TEXT,log_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
